import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import GradientBackground from "@/components/GradientBackground";
import FooterBackground from "@/components/Footer";
import Header from "@/components/Header";



const JetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={JetBrainsMono.variable}>
      <body>
        <div className="relative min-h-screen bg-[#0d1117] overflow-hidden">
          <GradientBackground />
          <Header />
          {/* Nội dung chính */}
          <main className="relative z-10 flex items-center justify-center min-h-[calc(100vh-110px)] px-4">
            {/* khoảng trống đã trừ header/footer */}
            <div className="max-w-3xl w-full">{children}</div>
          </main>
          <FooterBackground />
        </div>
      </body>
    </html>

  );
}
