import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import GradientBackground from "@/components/Templates/GradientBackground";
import FooterBackground from "@/components/Layout/Footer";
import Header from "@/components/Layout/Header";



const JetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={JetBrainsMono.variable}>
      <body>
        <div className="relative flex flex-col min-h-screen bg-[#0d1117] overflow-hidden">
          <GradientBackground />
          <Header />
          {/* Nội dung chính */}
          <main className="relative z-10 flex-1 flex flex-col w-full">
            <div className="flex-1 w-full h-screen">{children}</div>
          </main>
          <FooterBackground />
        </div>
      </body>
    </html>

  );
}
