import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'



const JetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${JetBrainsMono.variable} ${JetBrainsMono.variable} antialiased`}>
        <div>
          <header className="p-4 bg-gray-800 text-white">
            <nav>
              <ul className="flex space-x-4">
                <li><Link href="/hello">Contact</Link></li>
                <li><Link href="/about-me">About Me</Link></li>
                <li><Link href="/projects">Projects</Link></li>
              </ul>
            </nav>
          </header>

          <main>{children}</main>

          <footer className="mt-10 flex from-gray-900 to-blue-900 justify-between border-t border-gray-700 pt-4">
        <div className="text-green-400">find me in:</div>
        <div className="text-green-400">@daveinthahood</div>
      </footer>
        </div>
      </body>
    </html>
    // <html lang="en">
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    //     {children}
    //   </body>
    // </html>
  );
}
