import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import GradientBackground from "@/components/Templates/GradientBackground";
import FooterBackground from "@/components/Layout/Footer";
// import Header from "@/components/Layout/Header";
import ClientLayout from "@/components/Layout/ClientLayout";



const JetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={JetBrainsMono.variable}>
      <body>
        <div className="relative flex flex-col min-h-screen bg-[#0d1117] overflow-hidden">
          <GradientBackground children={undefined} />
         <ClientLayout>{children}</ClientLayout>
          <FooterBackground />
        </div>
      </body>
    </html>

  );
}
